# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Discli < Formula
  desc "Discord CLI + local daemon"
  homepage "https://github.com/patrickjm/discli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patrickjm/discli/releases/download/v0.1.1/discli_0.1.1_darwin_amd64.tar.gz"
      sha256 "321285eeb61036f9c65d3bb4dce19077123fd26894f8303ea0ebe08b17f7b7a9"

      def install
        bin.install "discli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patrickjm/discli/releases/download/v0.1.1/discli_0.1.1_darwin_arm64.tar.gz"
      sha256 "b7304d23ce188f6b9dd733860db7f25785cc15fe2a411cca4a1a5c2bce90690d"

      def install
        bin.install "discli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrickjm/discli/releases/download/v0.1.1/discli_0.1.1_linux_amd64.tar.gz"
      sha256 "454594a54da73a42df625226c98552d8635c998298fa46a662a6ac34599b7253"
      def install
        bin.install "discli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrickjm/discli/releases/download/v0.1.1/discli_0.1.1_linux_arm64.tar.gz"
      sha256 "1cdb8103a0b092edca6293b662253dbf4d06b91213646cb7a5dfe8ca639dbc35"
      def install
        bin.install "discli"
      end
    end
  end
end
