# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Api < Formula
  desc "api is a scriptable API client"
  homepage "https://github.com/patrickjm/api-cli"
  version "0.1.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/patrickjm/api-cli/releases/download/v0.1.3/api-cli_0.1.3_darwin_amd64.tar.gz"
    sha256 "279347e526930721004c9fc65ac2bde3e18e397982b9eab1eadc1d9d9b91e23e"

    def install
      bin.install "api"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/patrickjm/api-cli/releases/download/v0.1.3/api-cli_0.1.3_darwin_arm64.tar.gz"
    sha256 "9dd751cef12a9f97b6b5545e62b68bf9cffdfec271902eb3b6bbe3b5e7e35f20"

    def install
      bin.install "api"
    end
  end
end
