# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Discli < Formula
  desc "Discord CLI + local daemon"
  homepage "https://github.com/patrickjm/discli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patrickjm/discli/releases/download/v0.1.3/discli_0.1.3_darwin_amd64.tar.gz"
      sha256 "422c2f1b1400f1ade07af10fd6a0c005b613765aca46066e9f2e4165708bd9af"

      def install
        bin.install "discli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patrickjm/discli/releases/download/v0.1.3/discli_0.1.3_darwin_arm64.tar.gz"
      sha256 "3e7274dcac619ab5a8ca2684ce49aa5349a67cebd2f1e9b5f2f549a32eb25bd6"

      def install
        bin.install "discli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrickjm/discli/releases/download/v0.1.3/discli_0.1.3_linux_amd64.tar.gz"
      sha256 "3df97d1c6275af229cdc4e31156f0d4e681738b31a87db8015f450b4f771066e"
      def install
        bin.install "discli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrickjm/discli/releases/download/v0.1.3/discli_0.1.3_linux_arm64.tar.gz"
      sha256 "1aa792c3d9922dd43a83d4c268ae8725e8d87809d2b15242a648911c01ef8492"
      def install
        bin.install "discli"
      end
    end
  end
end
