# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keybox < Formula
  desc "Store reusable env var sets in macOS Keychain and emit .env files"
  homepage "https://github.com/patrickjm/keybox"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patrickjm/keybox/releases/download/v0.1.1/keybox_0.1.1_darwin_amd64.tar.gz"
      sha256 "103ea062e0d2b229f5c70f7a572f6d3d4570630b536b4d7316fcb6528fb6a8ff"

      def install
        bin.install "keybox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patrickjm/keybox/releases/download/v0.1.1/keybox_0.1.1_darwin_arm64.tar.gz"
      sha256 "a00d4ba0768ebbcc7f62227d45ab23555db618f3c2f1291d117bb2f339f65cff"

      def install
        bin.install "keybox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrickjm/keybox/releases/download/v0.1.1/keybox_0.1.1_linux_amd64.tar.gz"
      sha256 "1506a9632cd279305d7b6c87220c6ff3e7c8bd565a4a0eed4ef0beb1dd964cea"
      def install
        bin.install "keybox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrickjm/keybox/releases/download/v0.1.1/keybox_0.1.1_linux_arm64.tar.gz"
      sha256 "42ea7af178e98ead1c402a08f610019f426537f5d1a5870d3281326bedec11c6"
      def install
        bin.install "keybox"
      end
    end
  end

  test do
    system "#{bin}/keybox", "--help"
  end
end
