# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Www < Formula
  desc "Playwright-based CLI for persistent browser profiles and automation"
  homepage "https://github.com/patrickjm/www"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patrickjm/www/releases/download/v0.1.5/www_0.1.5_darwin_amd64.tar.gz"
      sha256 "cb67a5009f0e7ad00223b5e8a8c55f19f373a8870dbadf34f4be71998a44810f"

      def install
        bin.install "www"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patrickjm/www/releases/download/v0.1.5/www_0.1.5_darwin_arm64.tar.gz"
      sha256 "9f9ce41e0ba05b6d46a0cb375e0675d42c85cae4614e3824249bfc830dfd75c4"

      def install
        bin.install "www"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrickjm/www/releases/download/v0.1.5/www_0.1.5_linux_amd64.tar.gz"
      sha256 "79f8a2f968a6ef4ff3e1aea21caa86c268f313b958a1bc87e92277caf237c1a8"
      def install
        bin.install "www"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrickjm/www/releases/download/v0.1.5/www_0.1.5_linux_arm64.tar.gz"
      sha256 "2dd8531168f97a9f720a4759841f2c2cb577fff477b021c49012a50d02c4ccb3"
      def install
        bin.install "www"
      end
    end
  end

  test do
    system "#{bin}/www", "--help"
  end
end
