# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Www < Formula
  desc "Playwright-based CLI for persistent browser profiles and automation"
  homepage "https://github.com/patrickjm/www"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patrickjm/www/releases/download/v0.1.3/www_0.1.3_darwin_amd64.tar.gz"
      sha256 "cbba7f520fcb779ad21680054541dacdca1783f190fdaada835e58d8edee4c5d"

      def install
        bin.install "www"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patrickjm/www/releases/download/v0.1.3/www_0.1.3_darwin_arm64.tar.gz"
      sha256 "e707e9302863a91d46f5b5b0c7aa0630c2920e19ac4ad28dc965bd1849f95339"

      def install
        bin.install "www"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrickjm/www/releases/download/v0.1.3/www_0.1.3_linux_amd64.tar.gz"
      sha256 "b86c14b146ac129fcc4c58788be8e5d5338d9d3f408dd11245e845ea00b43ecd"
      def install
        bin.install "www"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrickjm/www/releases/download/v0.1.3/www_0.1.3_linux_arm64.tar.gz"
      sha256 "d6dc1e7f4c86c7fbf1f1cb2a3e131c464cab621c460fab9e36b70929c575e8a1"
      def install
        bin.install "www"
      end
    end
  end

  test do
    system "#{bin}/www", "--help"
  end
end
